import {
    MdMic,
    MdAutoFixHigh,
    MdShield,
    MdLocationOn,
    MdPhone,
    MdBusiness,
    MdCoffee,
    MdEmail,
    MdMenu,
    MdClose,
    MdCheckCircle,
    MdArrowForward,
    MdLock,
    MdSpeed,
    MdGroups,
    MdTrendingUp,
    MdTimeline,
    MdVerifiedUser,
    MdStorage,
    MdSmartToy,
    MdFlashOn,
    MdHistory,
    MdHandshake,
    MdLibraryAddCheck,
    MdLayers,
    MdCloudDone,
    MdOutlineSupportAgent,
    MdPublishedWithChanges
} from 'react-icons/md';

export {
    MdMic,
    MdAutoFixHigh,
    MdShield,
    MdLocationOn,
    MdPhone,
    MdBusiness,
    MdCoffee,
    MdEmail,
    MdMenu,
    MdClose,
    MdCheckCircle,
    MdArrowForward,
    MdLock,
    MdSpeed,
    MdGroups,
    MdTrendingUp,
    MdTimeline,
    MdVerifiedUser,
    MdStorage,
    MdSmartToy,
    MdFlashOn,
    MdFlashOn as MdZap,
    MdHistory,
    MdHistory as MdClockLoader3,
    MdHandshake,
    MdLibraryAddCheck,
    MdLayers,
    MdCloudDone,
    MdOutlineSupportAgent,
    MdPublishedWithChanges
};
